sudo: true
dist: trusty

language: python
python:
  - "3.4"

before_install:
  - ./.travis/install-dependencies.sh  

script:
  - ./functional_tests/test.sh collapse_cnvs-py
  - ./.travis/unit-test.sh
